exit if ruby build fails

diff --git a/bin/install-ruby b/bin/install-ruby
--- a/bin/install-ruby
+++ b/bin/install-ruby
@@ -1,16 +1,23 @@
 #!/usr/bin/env sh
 
-if [ -z "$1" ]; then
-  echo "Error: Ruby version is required as the first argument." >&2
+RUBY_VERSION="$1"
+if [ -z "$RUBY_VERSION" ]; then
+  echo "Ruby version is required as the first argument." >&2
   exit 1
 fi
-RUBY_VERSION="$1"
+
+function build_ruby() {
+  RUBY_CONFIGURE_OPTS="--disable-install-doc" rbenv install "$RUBY_VERSION"
+}
 
 echo "Installing Ruby version $RUBY_VERSION..."
 brew update
 brew upgrade
 rustup update
-RUBY_CONFIGURE_OPTS="--disable-install-doc" rbenv install "$RUBY_VERSION"
+if ! build_ruby; then
+  echo "\033[31mError: Failed to install Ruby version $RUBY_VERSION." >&2
+  exit 1
+fi
 rbenv rehash
 rbenv global "$RUBY_VERSION"
 gem update --system
